# Generated by Django 5.1.5 on 2025-01-30 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_gameinvitation_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameInvitation',
        ),
    ]
