# Generated by Django 4.2.16 on 2024-09-12 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player2_is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='pong.pongroom'),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], default='ongoing', max_length=10),
        ),
    ]
