# Generated by Django 4.2.16 on 2024-10-15 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pong', '0002_ponggame_finished_at_ponggame_player1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pongroom',
            name='max_players',
        ),
        migrations.AddField(
            model_name='pongroom',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_pong_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pongroom',
            name='pending_invitations',
            field=models.ManyToManyField(related_name='pending_pong_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pongroom',
            name='mode',
            field=models.CharField(choices=[('AI', 'AI'), ('CLASSIC', 'Classic'), ('RANKED', 'Ranked'), ('TOURNAMENT', 'Tournament')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pongroom',
            name='players',
            field=models.ManyToManyField(related_name='pong_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
