# Generated by Django 4.2.16 on 2024-10-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_remove_pongroom_max_players_pongroom_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongroom',
            name='state',
            field=models.CharField(choices=[('LOBBY', 'Lobby'), ('PLAYING', 'Playing')], default='LOBBY', max_length=20),
        ),
    ]
