# Generated by Django 5.1.5 on 2025-01-30 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_pongroom_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongroom',
            name='mode',
            field=models.CharField(choices=[('AI', 'AI Mode'), ('CLASSIC', 'Classic Mode'), ('RANKED', 'Ranked Mode'), ('TOURNAMENT', 'Tournament Mode')], default='AI', max_length=20),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='upcoming', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('pong_games', models.ManyToManyField(related_name='tournaments', to='pong.ponggame')),
                ('pong_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='pong.pongroom')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pong_game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pong.ponggame')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='pong.tournament')),
            ],
        ),
    ]
