# Generated by Django 5.1.6 on 2025-02-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_pongroom_mode_tournament_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongroom',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
