# Generated by Django 5.1.6 on 2025-02-20 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_pongroom_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='eliminated',
            field=models.ManyToManyField(blank=True, related_name='eliminated_tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
