# Generated by Django 5.1.7 on 2025-03-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_tournament_eliminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='player2_is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pongroom',
            name='mode',
            field=models.CharField(choices=[('AI', 'AI Mode'), ('LOCAL', 'Local Mode'), ('CLASSIC', 'Classic Mode'), ('RANKED', 'Ranked Mode'), ('TOURNAMENT', 'Tournament Mode')], default='AI', max_length=20),
        ),
    ]
