# Generated by Django 5.1.7 on 2025-03-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_ponggame_player2_is_guest_alter_pongroom_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongroom',
            name='mode',
            field=models.CharField(choices=[('AI', 'AI Mode'), ('LOCAL', 'Local Mode'), ('CLASSIC', 'Classic Mode'), ('TOURNAMENT', 'Tournament Mode')], default='AI', max_length=20),
        ),
    ]
