# Generated by Django 5.1.6 on 2025-02-10 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendrequests',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
