# Generated by Django 5.1.7 on 2025-03-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_twofa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_42_user',
            field=models.BooleanField(default=False),
        ),
    ]
